name: ci

on:
  workflow_dispatch:
  repository_dispatch:
    types: [upstream-updated]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Owner
        id: meta
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push (Docker Hub + GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
            linux/386
            linux/s390x
            linux/ppc64le
            linux/riscv64
          tags: |
            sheepgreen/switch-lan-play-client:latest
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/switch-lan-play-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
