name: upstream-watch

on:
  schedule:
    - cron: 8 6 * * *
  workflow_dispatch:

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Get upstream latest commit
        id: upstream
        uses: actions/github-script@v7
        with:
          script: |
            const owner = "spacemeowx2";
            const repo = "switch-lan-play";
            const repoInfo = await github.rest.repos.get({ owner, repo });
            const branch = repoInfo.data.default_branch;
            const { data: commits } = await github.rest.repos.listCommits({
              owner, repo, per_page: 1, sha: branch
            });
            const sha = commits[0].sha;
            core.setOutput("sha", sha);

      - name: Restore last SHA from cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .upstream-sha
          key: upstream-sha

      - name: Read last SHA
        id: last
        run: |
          if [ -f .upstream-sha ]; then
            echo "last=$(cat .upstream-sha)" >> $GITHUB_OUTPUT
          else
            echo "last=" >> $GITHUB_OUTPUT
          fi

      - name: Compare SHA and decide
        id: decide
        run: |
          if [[ "${{ steps.last.outputs.last }}" == "${{ steps.upstream.outputs.sha }}" ]]; then
            echo "changed=no" >> $GITHUB_OUTPUT
          else
            echo "changed=yes" >> $GITHUB_OUTPUT
          fi

      - name: Save new SHA
        if: steps.decide.outputs.changed == 'yes'
        run: |
          echo "${{ steps.upstream.outputs.sha }}" > .upstream-sha

      - name: Update cache with new SHA
        if: steps.decide.outputs.changed == 'yes'
        uses: actions/cache/save@v4
        with:
          path: .upstream-sha
          key: upstream-sha

      - name: Trigger docker build workflow
        if: steps.decide.outputs.changed == 'yes'
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: upstream-updated
